name: Downstream
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
  workflow_call:

run-name: Triggered by workflow_run_id ${{ github.event.workflow_run.id }}, upstream name ${{ github.event.workflow_run.name }}, run numb ${{ github.event.workflow_run.run_number }}

jobs:
  # This workflow contains a single job called "build"
  build:
    name: FirstJobDownstream
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
         EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo $EVENT_CONTEXT
        name: upstream_info
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - env:
         PAY: ${{ github.event.workflow_run.id }}
        run: echo $PAY
        name: workflow_run_id
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Shell 2
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Shell 3
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test:
   name: SecondJobDownstream
   runs-on: ubuntu-latest              
   steps: 
   # Runs a single command using the runners shell
      - name: Shell 1
        run: echo Hello, world!
